### PR TITLE
Feature 14 Routing + Tests

### PR DESCRIPTION
**Pull request by arikamat**

### CODE REVIEW

**Review by jerkur22 — APPROVED** [review]

**Comment by arikamat** [comment]
[Task 7: Integrate Frontend with Authentication API](https://trello.com/c/5URm5jCL/8-task-7-integrate-frontend-with-authentication-api)

**Comment by arikamat** [comment]
[Task 7: Integrate Frontend with Authentication API](https://trello.com/c/5URm5jCL/8-task-7-integrate-frontend-with-authentication-api)

**Comment by arikamat** [comment]
[Task 14: Set up Basic Routing/Navigation for the Dashboard](https://trello.com/c/sTO9L6D2/15-task-14-set-up-basic-routing-navigation-for-the-dashboard)

**Comment by arikamat** [comment]
[Task 16.5 Create Unit Tests for Routing and Navbar](https://trello.com/c/i3iNd2zM/20-task-165-create-unit-tests-for-routing-and-navbar)

**Pull request merged**
